insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/chessboard/rss20.xml','FORZA 浦和レッズ','FORZA 浦和レッズ',now());
insert into redsFeedMaster values(default,'http://sanukireds.ashita-sanuki.jp/index.rdf','J for 2014','J for 2014',now());
//insert into redsFeedMaster values(default,'http://www.redspress.jp/index/reds_eyes/INDEX7/','REDSPRESS EYES','レッズプレス！！',now());
insert into redsFeedMaster values(default,'http://gdata.youtube.com/feeds/base/users/URAWAREDSBBB/uploads?alt=rss&v=2&orderby=published&client=ytapi-youtube-profile','Uploads by URAWAREDSBBB','Uploads by URAWAREDSBBB',now());
insert into redsFeedMaster values(default,'http://uragi.com/atom.xml','浦議','浦議',now());
insert into redsFeedMaster values(default,'http://pipes.yahoo.com/pipes/pipe.run?_id=19673e3f31f52639233561b39f6dacff&_render=rss','UrawaReds','',now());
insert into redsFeedMaster values(default,'http://yaplog.jp/redspride/index1_0.rdf','★  ダイヤの夜明け～浦和紅宝石～','★  ダイヤの夜明け～浦和紅宝石～',now());
insert into redsFeedMaster values(default,'http://yaplog.jp/shimashima1426/index1_0.rdf','☆そろそろ行こうか        浦和レッズ☆','☆そろそろ行こうか        浦和レッズ☆',now());
insert into redsFeedMaster values(default,'http://api.plaza.rakuten.ne.jp/superking/rss/','おうさまの浦和レッズ的サッカー生活！','おうさまの浦和レッズ的サッカー生活！',now());
insert into redsFeedMaster values(default,'http://blog.livedoor.jp/no3_12/index.rdf','じゅにじゅに','じゅにじゅに',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/escudero-001/rss20.xml','セルヒオ・アリエル・エスクデロオフィシャルブログ Powered by Ameba','セルヒオ・アリエル・エスクデロオフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/reds-internet-club/rss20.xml','レッズインターネットクラブ | 浦和レッズブログ','レッズインターネットクラブ',now());
//insert into redsFeedMaster values(default,'http://www.redspress.jp/index/reds_kobore/INDEX7/','レッズプレス　こぼれ話','レッズプレス！！',now());
//insert into redsFeedMaster values(default,'http://www.redspress.jp/index/reds_misitemuryo/INDEX7/','レッズプレス　その他','レッズプレス！！',now());
//insert into redsFeedMaster values(default,'http://www.redspress.jp/index/reds_heartbeat/INDEX7/','レッズプレス　ハートビート','レッズプレス！！',now());
//insert into redsFeedMaster values(default,'http://www.redspress.jp/index/reds_renshurepo/INDEX7/','レッズプレス　練習レポート','レッズプレス！！',now());
//insert into redsFeedMaster values(default,'http://www.redspress.jp/index/reds_redsnews/INDEX7/','レッズプレス！！','レッズプレス！！',now());
insert into redsFeedMaster values(default,'http://gree.jp/kato_nobuhiro/blog/52c25fee41274e650e9988155e94e9f7.rdf','加藤順大 公式ブログ - GREE','加藤順大 公式ブログ',now());
insert into redsFeedMaster values(default,'http://gree.jp/haraguchi_genki/blog/e973e67405e976972e349a39c47ce392.rdf','原口元気 公式ブログ - GREE','原口元気 公式ブログ',now());
insert into redsFeedMaster values(default,'http://www.plus-blog.sportsnavi.com/redine/atom/feed.xml','地球は青い！','地球は青い！',now());
insert into redsFeedMaster values(default,'http://www.plus-blog.sportsnavi.com/redspride/atom/feed.xml','太平洋を越えて','太平洋を越えて',now());
insert into redsFeedMaster values(default,'http://gree.jp/ugajin_tomoya/blog/9536c22c436c09086feb440013a20a9d.rdf','宇賀神友弥 公式ブログ - GREE','宇賀神友弥 公式ブログ',now());
insert into redsFeedMaster values(default,'http://pure-city.jp/gk-gishi/index.xml','山岸範宏オフィシャルブログ - THE GUARDIAN','山岸範宏オフィシャルブログ - THE GUARDIAN',now());
insert into redsFeedMaster values(default,'http://footballerplus.net/yamagishi/?feed=rss2','山岸範宏公式ブログ | THE GUARDIAN','山岸範宏公式ブログ | THE GUARDIAN',now());
insert into redsFeedMaster values(default,'http://yamadanobuhisa.jp/?feed=rss2','山田暢久オフィシャルブログ','山田暢久オフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/yohsuke0223/rss20.xml','新生レッズの逆襲','新生レッズの逆襲',now());
insert into redsFeedMaster values(default,'http://lineblog.me/kashiwagiyosuke/site.css?_=20160215204959','柏木陽介 オフィシャルブログ Powered by Ameba','柏木陽介 オフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/tsukasa-umesaki/rss20.xml','梅崎司 オフィシャルブログ Powered by Ameba','梅崎司 オフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://feedblog.ameba.jp/rss/ameblo/ryota-moriwaki/rss20.xml','森脇良太オフィシャルブログ Powered by Ameba','森脇良太オフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://samurai-foot.com/urawareds/feed/atom/','歌え浦和の男なら！！','歌え浦和の男なら！！',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/takeshi-mizuuchi/rss20.xml','水内猛オフィシャルブログ「オフサイドぎりぎり！」Powered by Ameba','水内猛オフィシャルブログ「オフサイドぎりぎり！」',now());
insert into redsFeedMaster values(default,'http://www.urawa-football.com/feed/','浦和フットボール通信','浦和フットボール通信',now());
insert into redsFeedMaster values(default,'http://webryblog.biglobe.ne.jp/a/8/a85a908aa2/themeindex.rdf','浦和レッズ ブログ | 記事一覧 | ウェブリブログ','',now());
insert into redsFeedMaster values(default,'http://gree.jp/urawa_reds/blog/3bb66e7e5b9713b6a843df8b2b09a9cd.rdf','浦和レッズ 公式ブログ - GREE','浦和レッズ 公式ブログ',now());
insert into redsFeedMaster values(default,'http://redsgyakushuu.blog.shinobi.jp/RSS/','浦和レッズの逆襲日報','浦和レッズの逆襲日報',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/forever-reds1104/rss20.xml','浦和レッズを綴るブログ　－赤い里の庵の翁－','浦和レッズを綴るブログ　－赤い里の庵の翁－',now());
insert into redsFeedMaster values(default,'http://urawaredsblog.blogspot.com/feeds/posts/default','浦和レッズブログ blogger','浦和レッズブログ blogger',now());
insert into redsFeedMaster values(default,'http://www.uracolle.com/feeds/posts/default','浦和レッズ好きのためのコレ：浦コレ','浦和レッズ好きのためのコレ：浦コレ',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/sickham/rss20.xml','浦和レッズ応援ブログ','浦和レッズ応援ブログ',now());
insert into redsFeedMaster values(default,'http://www.facebook.com/feeds/page.php?format=rss20&id=366946266659458','浦和レッドダイヤモンズ Facebook Wall','浦和レッズ Facebook Wall',now());
insert into redsFeedMaster values(default,'http://reds-nation.tumblr.com/rss','浦和三昧','浦和三昧',now());
insert into redsFeedMaster values(default,'http://www.plus-blog.sportsnavi.com/feed/stag/9/rss2_0.xml','浦和（J）','',now());
insert into redsFeedMaster values(default,'http://www.targma.jp/urakenplus/feed','浦研プラス','浦研プラス',now());
insert into redsFeedMaster values(default,'http://muuuiiremkg.blog111.fc2.com?xml','無右の部屋','無右の部屋',now());
insert into redsFeedMaster values(default,'http://urawa.way-nifty.com/yonoreds/atom.xml','與野レッズBlog','與野レッズBlog',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/suzuki-keita-blog/rss20.xml','鈴木啓太オフィシャルブログPowered by Ameba','鈴木啓太オフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://footballerplus.net/sekiguchi/?feed=rss2','関口訓充公式ブログ | Route du monde','関口訓充公式ブログ | Route du monde',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/reds310/rss20.xml','頂点を目指して','頂点を目指して',now());
insert into redsFeedMaster values(default,'http://www.plus-blog.sportsnavi.com/pride-of-urawa/atom/feed.xml','日本サッカーの世界制覇を夢見て…','日本サッカーの世界制覇を夢見て…',now());
insert into redsFeedMaster values(default,'http://urawaredsblogger.seesaa.net/index.rdf','浦和レッズブロガー','浦和レッズブロガー',now());
insert into redsFeedMaster values(default,'http://urawareds-ouen.seesaa.net/index.rdf','北浦和から浦和レッズを応援するブログ','北浦和から浦和レッズを応援するブログ',now());
insert into redsFeedMaster values(default,'http://feedblog.ameba.jp/rss/ameblo/hiromi0013/rss20.xml','赤き血のガッパの浦和レッズへの毒舌ブログ','赤き血のガッパの浦和レッズへの毒舌ブログ',now());
insert into redsFeedMaster values(default,'http://goredsgo.com/feed/','浦和レッズ  情報ブログ　“なんでもレッズ”','浦和レッズ  情報ブログ　“なんでもレッズ”',now());
insert into redsFeedMaster values(default,'http://redsomoroi.seesaa.net/index.rdf','浦和レッズって面白い','浦和レッズって面白い',now());
insert into redsFeedMaster values(default,'http://ameblo.jp/lee-tadanari/','李忠成OFFICIAL BLOG','李忠成OFFICIAL BLOG',now());
insert into redsFeedMaster values(default,'http://www.facebook.com/feeds/page.php?format=rss20&id=330021607141206','森脇良太 Facebook','森脇良太 Facebook',now());
insert into redsFeedMaster values(default,'http://bloglife9.blog97.fc2.com/?xml','サッカー bloglife','サッカー bloglife',now());
insert into redsFeedMaster values(default,'http://blogs.yahoo.co.jp/grazieurawa','grazieurawaの 浦和レッズダイアリー','grazieurawaの 浦和レッズダイアリー',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/minazuki1961/rss20.xml','突き上げた拳の向こうに','突き上げた拳の向こうに',now());
insert into redsFeedMaster values(default,'http://blogs.yahoo.co.jp/grazieurawa/rss.xml','grazieurawaの 浦和レッズダイアリー','grazieurawaの 浦和レッズダイアリー',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/seiizu777/rss20.xml','レッズ好きのブログ','レッズ好きのブログ',now());
insert into redsFeedMaster values(default,'http://blogs.yahoo.co.jp/amamin2000/rss.xml','ビールが主食～あまぱぱ【拉麺男】YOU-SUCK!!参戦記♪','ビールが主食～あまぱぱ【拉麺男】YOU-SUCK!!参戦記♪',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/redstrust/rss20.xml','redstrustの浦和レッズつれづれ','redstrustの浦和レッズつれづれ',now());
insert into redsFeedMaster values(default,'http://feeds.feedburner.com/pride-of-urawa','Keep on Jumpin''','Keep on Jumpin''',now());
insert into redsFeedMaster values(default,'http://rssblog.ameba.jp/mono-komo/rss20.xml','浦和レッズとあなたに乾杯','浦和レッズとあなたに乾杯',now());
insert into redsFeedMaster values(default,'http://lineblog.me/endowataru/index.rdf','遠藤航 公式ブログ','遠藤航 公式ブログ',now());
insert into redsFeedMaster values(default,'http://lineblog.me/kashiwagiyosuke/index.rdf','柏木陽介 オフィシャルブログ','柏木陽介 オフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://lineblog.me/ugajintomoya/index.rdf','宇賀神友弥オフィシャルブログ','宇賀神友弥オフィシャルブログ',now());
insert into redsFeedMaster values(default,'http://lineblog.me/mr_makino0511/index.rdf','槙野智章オフィシャルブログ','槙野智章オフィシャルブログ',now());


insert into redsFeedMaster values(default,'http','xx','xx',now());
