insert into visselFeedMaster values(default,'http://pipes.yahoo.com/pipes/pipe.run?_id=ba6202724d182f786268dd4b58944935&_render=rss','Vissel Kobe','',now());
insert into visselFeedMaster values(default,'http://www.facebook.com/feeds/page.php?format=rss20&id=217897084965724','ヴィッセル神戸 Facebook','ヴィッセル神戸 Facebook',now());
insert into visselFeedMaster values(default,'http://api.plaza.rakuten.ne.jp/vissel83/rss/','VISSELやっさんBLOG ','VISSELやっさんBLOG ',now());
insert into visselFeedMaster values(default,'http://jocr.jp/blog/xml-rss2.php?blogid=19','GOGO!ヴィッセル神戸ブログ','GOGO!ヴィッセル神戸ブログ',now());
insert into visselFeedMaster values(default,'http://vissel950.blog.fc2.com/?xml','トモニ行くぜ！ヴィッセル神戸！','トモニ行くぜ！ヴィッセル神戸！',now());
insert into visselFeedMaster values(default,'http://pakila.jp/hashimoto/diary/feed/','橋本英郎公式サイト「絆」','橋本英郎公式サイト「絆」',now());
insert into visselFeedMaster values(default,'http://club.kobe-np.co.jp/vissel/?feed=rss2&cat=4','Live! Vissel ','Live! Vissel ',now());
insert into visselFeedMaster values(default,'http://club.kobe-np.co.jp/vissel/?feed=rss2&cat=3','Live! Vissel','Live! Vissel',now());
insert into visselFeedMaster values(default,'http://club.kobe-np.co.jp/vissel/?feed=rss2&cat=5','Live! Vissel','Live! Vissel',now());
insert into visselFeedMaster values(default,'http://blogs.yahoo.co.jp/seiwadai_nobu/rss.xml','いつも心にヴィッセルを','いつも心にヴィッセルを',now());
insert into visselFeedMaster values(default,'http://api.plaza.rakuten.ne.jp/visselsupporter/rss/','神戸魂','神戸魂',now());
insert into visselFeedMaster values(default,'http://api.plaza.rakuten.ne.jp/visselashiya/rss/','VISSEL KOBEとｺﾍﾞﾙｺｽﾃｨ-ﾗ-ｽﾞ■□応援します、Ashiyaから','VISSEL KOBEとｺﾍﾞﾙｺｽﾃｨ-ﾗ-ｽﾞ■□応援します、Ashiyaから',now());
insert into visselFeedMaster values(default,'http://mikoko2008.blog60.fc2.com/?xml','神戸たまごのヴィッセル応援日記','神戸たまごのヴィッセル応援日記',now());
insert into visselFeedMaster values(default,'http://kobe.kensyusokko.com/feed/','けしゅんそこっう ～堅守速攻？','けしゅんそこっう ～堅守速攻？ ',now());
insert into visselFeedMaster values(default,'http://rssblog.ameba.jp/shunki-takahashi/rss20.xml','高橋峻希オフィシャルブログ','高橋峻希オフィシャルブログ',now());
insert into visselFeedMaster values(default,'http://api.plaza.rakuten.ne.jp/koberiver/rss/','がんばれヴィッセル神戸～koberiverのブログ','がんばれヴィッセル神戸～koberiverのブログ',now());
insert into visselFeedMaster values(default,'http://rss.phew.homeip.net/v10/10026.xml','ヴィッセル神戸公式','ヴィッセル神戸公式',now());
insert into visselFeedMaster values(default,'https://api.plaza.rakuten.ne.jp/visselashiya/rss/','VISSEL KOBEとｺﾍﾞﾙｺｽﾃｨ-ﾗ-ｽﾞ■□応援します、Ashiyaから','VISSEL KOBEとｺﾍﾞﾙｺｽﾃｨ-ﾗ-ｽﾞ■□応援します、Ashiyaから',now());
insert into visselFeedMaster values(default,'http://dojidojid.blog40.fc2.com/?xml','よっしぃの徒然なるままに・・・','よっしぃの徒然なるままに・・・',now());
insert into visselFeedMaster values(default,'https://api.plaza.rakuten.ne.jp/1995117vissel/rss/','考え事ほか','考え事ほか',now());
insert into visselFeedMaster values(default,'http://blog.livedoor.jp/kaisei_kanren/index.rdf','神戸海征塾＆関西蹴球國士連合公式BLOG','神戸海征塾＆関西蹴球國士連合公式BLOG',now());
insert into visselFeedMaster values(default,'https://api.plaza.rakuten.ne.jp/visselsupporter/rss/','神戸魂','神戸魂',now());
insert into visselFeedMaster values(default,'https://api.plaza.rakuten.ne.jp/visselist/rss/','臙脂の闘志   ヴィッセル応援大陸','臙脂の闘志   ヴィッセル応援大陸',now());
insert into visselFeedMaster values(default,'https://api.plaza.rakuten.ne.jp/koberiver/rss/','がんばれヴィッセル神戸～koberiverのブログ','がんばれヴィッセル神戸～koberiverのブログ',now());
insert into visselFeedMaster values(default,'https://lineblog.me/tanakajunya/index.rdf','田中順也 公式ブログ','田中順也 公式ブログ',now());

insert into visselFeedMaster values(default,'http','xx','xx',now());
